### PR TITLE
allow polling multiple RabbitMQ hosts

### PR DESCRIPTION
**Pull request by nathanleiby**
The current version allows only polling a single RabbitMQ host. You can now pass a JSON / Yaml config to specify multiple hosts to poll.

### CODE REVIEW

**Comment by dfuentes** [comment]
LGTM.  It may also be useful to check in the generated `glide.lock` file that gets created when you do glide install to ensure the build is entirely reproducible.

**Comment by nathanleiby** [comment]
@dfuentes added `glide.lock` 9e41d9b

I also:

- added hostname to the log output
- updated to use Kayvee v3

**Comment by nathanleiby** [comment]
Should commit shas be entirely removed from `glide.yaml` now?

**Comment by dfuentes** [comment]
lgtm, I think the glide.yaml is good as is.

**Pull request merged**
